name: PreSubmit-Build

on:
  pull_request:

jobs:
  build:
    name: Build NGINX OCI image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nginx-version: [1.20.2, 1.23.0]

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2.0.0

    - name: Generate snapshot date
      id: snapshot-date
      run: |
        echo ::set-output name=date::$(date -u +%Y%m%d)
      shell: bash


    - uses: sigstore/cosign-installer@main
    - uses: priyawadhwa/actions-1/melange-build@main
      with:
        sign-with-temporary-key: true
        config: melange.yaml
        empty-workspace: true
        archs: x86_64,aarch64,armv7
        # template: "{\"Version\": \"${{ matrix.nginx-version }}\" }"

    - uses: distroless/actions/apko-build@main
      with:
        config: apko.yaml
        tag: nginx:${{ steps.snapshot-date.outputs.date }}
        keyring-append: /github/workspace/melange.rsa.pub
        archs: x86_64,aarch64,armv7
        source-date-epoch: ${{ steps.snapshot-date.outputs.epoch }}
        additional-tags: ${{ matrix.nginx-version }}

    - uses: actions/upload-artifact@v3
      with:
        name: nginx.tar
        path: ./output.tar
